#!/usr/bin/env bash

set -e

# Configure Document Root
mkdir -p ${NGINX_SERVER_ROOT}
chown www-data:www-data ${NGINX_SERVER_ROOT}

# Configure PHP
PHP_INI_PATH=/etc/php7/conf.d
echo "date.timezone = ${PHP_TIMEZONE}" > ${PHP_INI_PATH}/timezone.ini
XDEBUG_INI_DISABLED=${PHP_INI_PATH}/xdebug.ini.disabled
XDEBUG_INI_ENABLED=${PHP_INI_PATH}/xdebug.ini
XDEBUG_INI_REMOTE_HOST=${PHP_INI_PATH}/xdebug_remote_host.ini

# Configure Nginx
NGINX_CONFIG=/etc/nginx/conf.d/default.conf
cp ${NGINX_CONFIG}.tmpl ${NGINX_CONFIG}
sed -i "s|\$NGINX_SERVER_ROOT|${NGINX_SERVER_ROOT}|g" ${NGINX_CONFIG}
sed -i "s|\$NGINX_HEALTH_CHECK_PATH|${NGINX_HEALTH_CHECK_PATH}|g" ${NGINX_CONFIG}

# Configure PHP-FPM
PHPFPM_CONFIG=/etc/php7/php-fpm.conf
cp ${PHPFPM_CONFIG}.tmpl ${PHPFPM_CONFIG}
sed -i "s|\$PHPFPM_PM_MAX_CHILDREN|${PHPFPM_PM_MAX_CHILDREN}|g" ${PHPFPM_CONFIG}
sed -i "s|\$PHPFPM_PM_START_SERVERS|${PHPFPM_PM_START_SERVERS}|g" ${PHPFPM_CONFIG}
sed -i "s|\$PHPFPM_PM_MIN_SPARE_SERVERS|${PHPFPM_PM_MIN_SPARE_SERVERS}|g" ${PHPFPM_CONFIG}
sed -i "s|\$PHPFPM_PM_MAX_SPARE_SERVERS|${PHPFPM_PM_MAX_SPARE_SERVERS}|g" ${PHPFPM_CONFIG}
sed -i "s|\$PHPFPM_PM_MAX_REQUESTS|${PHPFPM_PM_MAX_REQUESTS}|g" ${PHPFPM_CONFIG}

# Enable XDebug if needed
if [ "${XDEBUG_ENABLE}" = "1" ]; then
    echo "nginx-entrypoint: Enable XDebug.."
    if [ -f "${XDEBUG_INI_DISABLED}" ]; then
        mv ${XDEBUG_INI_DISABLED} ${XDEBUG_INI_ENABLED}
    fi;
    # Configure XDebug remote host
    if [ -z "${XDEBUG_HOST}" ]; then
        # Allows to set XDEBUG_HOST by env variable because could be different from the one which come from ip route command
        XDEBUG_HOST=$(/sbin/ip route|awk '/default/ { print $3 }')
    fi;
    echo "nginx-entrypoint: Set XDebug remote host \"${XDEBUG_HOST}\""
    echo "xdebug.remote_host=${XDEBUG_HOST}" > ${XDEBUG_INI_REMOTE_HOST}
else
    if [ -f "${XDEBUG_INI_ENABLED}" ]; then
        mv ${XDEBUG_INI_ENABLED} ${XDEBUG_INI_DISABLED}
    fi;
    if [ -f "${XDEBUG_INI_REMOTE_HOST}" ]; then
      rm ${XDEBUG_INI_REMOTE_HOST}
    fi;
fi;

# Run PHP-FPM
echo "nginx-entrypoint: Run php-fpm with /etc/php7/php-fpm.conf"
php-fpm7 -D --fpm-config /etc/php7/php-fpm.conf

# Run Nginx
echo "nginx-entrypoint: Run command \"$@\""
exec "$@"
