#!/usr/bin/env bash

# Sources: https://www.sys-dev.cat/blog/5/

URL="https://www.cloudflare.com"
INTERNET_PROTOCOL="ips-v4 ips-v6"

TMP_CFG="/tmp/cloudflare.conf"
NGINX_CFG="/etc/nginx/conf.d/00_trusted_proxies.conf"

USE_X_FORWARDED_FOR="true"

check_nginx(){
    2>&1 nginx -V | xargs -n1 | grep with-http_realip_module >/dev/null || abort "Please recompile nginx with realip module support"
}

abort() {
    echo "$1";
    exit 1;
}

get() {
    rm -f "$2"
    /usr/bin/wget "$1" -O "$2" >/dev/null 2>&1 || abort "Error downloading $2"
}

replace(){
    cp -f "$1" "$2"
    nginx -t >/dev/null 2>&1 || abort "Something went wrong, please review nginx -t output"
    pkill -HUP nginx
}

# Check if nginx has realip module support
check_nginx

# Get the ip lists from cloudflare, fail if something goes wrong
for protocol in ${INTERNET_PROTOCOL}
do
    get "${URL}/${protocol}" "/tmp/${protocol}"
done

# remove the previous tmp file if exists
rm -f ${TMP_CFG}

# Recreate the file starting with this comment
echo "# Cloudflare Stuff:" >> "${TMP_CFG}"

# For each ip/network in each file create a line for the real ip module.
for protocol in ${INTERNET_PROTOCOL}
do
    for ip in `cat "/tmp/${protocol}"`
    do
        echo "set_real_ip_from ${ip};" >> "${TMP_CFG}"
    done
done

# Use the X-Forwarded-For: header, alternatively you can use:
# real_ip_header CF-Connecting-IP;
if [ "${USE_X_FORWARDED_FOR}" == "true" ]
then
    echo "real_ip_header X-Forwarded-For;" >> "${TMP_CFG}"
else
    echo "real_ip_header CF-Connecting-IP;" >> "${TMP_CFG}"
fi

# Compare the generated file with the previous file, if needed replace and reload nginx.
/usr/bin/diff "${NGINX_CFG}" "${TMP_CFG}"
if [ $? -ne 0 ]
then
    echo "IP changes, replace the config"
    replace "${TMP_CFG}" "${NGINX_CFG}"
else
    echo "No change"
fi

# Remove the new temporal file
rm -f "${TMP_CFG}" "${TMP_CFG}.diff"
